### ISSUE TITLE
Feature Request 1.19.2

### ISSUE THREAD

**Issue by celsiusqc** [BrokenK3yboard/UsefulSpyglass#1]
Could you add a config option where it would show the full namespace of what we are looking at?

Could also be a keybind toggle, where it would show: alexsmobs:elephant
or
create:brass_block

Also, for the 
#If enabled, block image and name will be displayed
"Display blocks" = true

Could you make a keybind that toggles this in game?

**Comment by BrokenK3yboard** [comment]
What's the justification for these features? I also refrain from adding keybinds unless there is a good reason to do so.
