### ISSUE TITLE
[1.20.1] Weird render issues, especially when used with paper doll mod

### ISSUE THREAD

**Issue by BugmanBugman** [BrokenK3yboard/UsefulSpyglass#3]
Just some weird issues with the health plate
![2023-09-18_12 58 47](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/40730042/cf0fabc6-be65-4b5f-885d-0751e18510ca)
![2023-09-18_12 58 51](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/40730042/28a8d8f7-13ac-4743-8d2f-51e8d1c655c3)
![2023-09-18_12 59 11](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/40730042/f3a91685-8bb2-4b15-b2ec-a11dfbe1d3cb)
![2023-09-18_12 59 12](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/40730042/2266e983-f310-4f87-9c4a-d8f1637cf1b0)
![2023-09-18_13 00 36](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/40730042/e6dd1e0a-689f-4c71-98e9-344505e55a37)
As you can see, some of them occur with the paper doll mod https://www.curseforge.com/minecraft/mc-mods/new-paper-doll, but some of them occur for no reason at all (no namesfor the creatures)

**Comment by BrokenK3yboard** [comment]
You will have to open an issue on their github asking why their mod is interfering with Mojang's tooltip text render.
