### ISSUE TITLE
Bug: looking at dropped item displays name of last seen block

### ISSUE THREAD

**Issue by robosoup2** [BrokenK3yboard/UsefulSpyglass#5]
this happens even if block names are disabled
so you can look at a block, exit spyglass, walk away, and zoom in on a dropped item and it will show the name of a block that's nowhere to be seen.

**Comment by robosoup2** [comment]
[video
](https://streamable.com/n9swny)

**Comment by BrokenK3yboard** [comment]
Should be fixed in version 0.5.1.
