### ISSUE TITLE
Empty tooltip is shown if block I look at is in reach

### ISSUE THREAD

**Issue by CatAndPaste** [BrokenK3yboard/UsefulSpyglass#6]
Small visual bug. If I look at block that is out of reach, block name is shown perfectly fine (img 1).

![img 1](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/85940028/7020ae5c-b69f-4c39-ad47-6f0b05833224)

But if I move closer, and block is reachable (can interact with it, black outline around and also Jade tooltip appears), empty tooltip is shown (img 2) which just doesn't look clean.

![img 2](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/85940028/1395fa73-8a8e-4a41-8a92-a6ed90ee87a8)

**Comment by BrokenK3yboard** [comment]
Latest update with attempted fix should be up.
