### ISSUE TITLE
Entities names are not displayed in survival mode

### ISSUE THREAD

**Issue by CyberRat7** [BrokenK3yboard/UsefulSpyglass#8]
![2024-03-06_16 12 53](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/131731394/fe954968-9096-4822-9cf2-a42e3207e9d1)
![2024-03-06_16 12 36](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/131731394/366fa674-f0ff-418b-8ab8-d50ee1f9d599)
This is on the most recent version (0.5.1) Forge, block names are fine but in survival mode entity names are still not displayed

**Comment by BrokenK3yboard** [comment]
List any mods which add HUD elements and uninstall them to see if the issue still occurs.

**Comment by CyberRat7** [comment]
It was the Combat Roll mod https://www.curseforge.com/minecraft/mc-mods/combat-roll dont know if its fix-able or not

**Comment by CKenJa** [comment]
cause of this bug is not combat-roll.

**Comment by CyberRat7** [comment]
The cause of the bug was combat roll for me, as he said any mods that are HUD elements can cause this problem so check for other mods too

**Comment by BrokenK3yboard** [comment]
Latest update with attempted fix should be up on Modrinth now, and Curseforge later.
