### ISSUE TITLE
[Crash] 0.6.0 causes crash during game startup

### ISSUE THREAD

**Issue by ClockworkCorvus** [BrokenK3yboard/UsefulSpyglass#9]
Version: Minecraft 1.20.1 with Neoforge 47.1.104

I installed the latest update this morning and the game crashed during loading, and despite my extensive modlist, it worked just fine the other day so I figured I'd send the log in case you can decipher it. There has to have been something that has changed that my game doesn't like.

Log: https://mclo.gs/UWyFVj0

**Comment by BrokenK3yboard** [comment]
There's nothing in the log that suggests my mod is the problem. Make sure you are posting the correct log.

**Comment by ElRichiRicon** [comment]
I have the same issue. I've narrowed it down to this mod with Create Central Kitchen. I'll also open an issue there.

1.20.1 with NeoForge 47.1.104

[prism log](https://pastebin.com/mrew6vJu)

**Comment by BrokenK3yboard** [comment]
Attempted fix should be up on Modrinth now, and Curseforge shortly. Reopen this issue if the error still occurs.
